package com.hoolai.access.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DB_USER".
 */
public class DbUser {

    private String account;
    /** Not-null value. */
    private String password;
    private String desc;
    /** Not-null value. */
    private java.util.Date date;

    public DbUser() {
    }

    public DbUser(String account) {
        this.account = account;
    }

    public DbUser(String account, String password, String desc, java.util.Date date) {
        this.account = account;
        this.password = password;
        this.desc = desc;
        this.date = date;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    /** Not-null value. */
    public java.util.Date getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(java.util.Date date) {
        this.date = date;
    }

}
